In [1]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])
## list인데 저렇게 묶어놓은 걸 tuple이라고한단다.

<class 'tuple'>
1
2
[3, '4']


In [3]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

In [4]:
import numpy as np ## import : 기본적인 것 외의 기능을 쓰기위해 numpy 폴더를 가져오는 것.
b = np.array(a) ## as : numpy를 np로 편하게 임의로 지정할 수 있음. 꼭 쓸필요는 없음. np 안에 있는 함수 array를 쓸려면 np.array라고 써야함
print(b) ##array는 그냥 matrix 같은 것임.
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [5]:
print(b*b) # element by element 끼리 곱해짐. 일반적인 행렬의 곱셈이 X

[[ 1  4  9]
 [ 9 64  0]]


In [6]:
c = np.matrix(b) ##진짜 행렬로 만들어줌
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [8]:
c*c # 진짜 행렬은 2:3 x 2:3 안됨. array와의 차이!

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [9]:
c*c.T # c.T 하면 2:3을 3:2로 transpose 해줌.

matrix([[14, 19],
        [19, 73]])